### ISSUE TITLE
Dev branch is broken after commit 34edafd

### ISSUE THREAD

**Issue by viktorsmari** [piratar/wasa2il#197]
After this commit: 34edafd2b858388a63393a22baba21183a2bde98

The following command:
`python manage.py runserver 0.0.0.0:8000` 

Gives this error:
 > AttributeError: 'Settings' object has no attribute 'FEATURES'

**Comment by helgihg** [comment]
Existing local_settings.py must be updated to include the value. New installations, without a local_settings.py won't be affected this way, because in the absence of local_settings.py, default_settings.py is used, which includes the setting.

**Comment by helgihg** [comment]
I wonder if there's a general way of catching this particular error and somehow instructing the user. Still, it may just be one of those things that you have to know or figure out, I'm not sure.

**Comment by viktorsmari** [comment]
Confirmed that new installations are not affected. 

Closing.
